services:
  - type: web
    name: acw-bot
    env: node
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: NODE_VERSION
        value: 20.18.0
      - key: DISCORD_TOKEN
        sync: false
